### ISSUE TITLE
Error in plot_pc_variance_explained

### ISSUE THREAD

**Issue by garfieldyc** [cole-trapnell-lab/monocle2-rge-paper#1]
Hi, I am beginner in R. I tried to run through the script prepare_HSMM_data.R. When it reached line 107, it threw out an error.

![image](https://user-images.githubusercontent.com/30006828/32411270-dbdcfa54-c1ac-11e7-83df-4f4cca6ab8c0.png)
 
I tried to ran the code on Mac and PC, and both showed the same error. 
My R version is 3.4.2 (2017-09-28). Could help me check with it?

Thank you,

**Comment by Xiaojieqiu** [comment]
check this link: https://github.com/cole-trapnell-lab/monocle-release/issues/58

**Comment by garfieldyc** [comment]
Thanks. It works when installing the latest package from github.

**Comment by marzamKI** [comment]
Hi.
I also experience this problem: I have downloaded the latest version of irlba I could find on github (2.3.1), but it still gives me this error.
Any idea what I should fix?
Thanks!

**Comment by Xiaojieqiu** [comment]
the newest version from irlba from github should be 2.3.2
